# Generated by Django 3.2.20 on 2023-08-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Easy', 'Easy')], max_length=10, null=True),
        ),
    ]
